# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='input',
        ),
        migrations.AddField(
            model_name='person',
            name='result',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
